/*
 *  VJXGUIConstants.h
 *  VeeJay
 *
 *  Created by Igor Sutton on 10/21/10.
 *  Copyright 2010 Dyne.org. All rights reserved.
 *
 */

#define ENTITY_OUTLET_HEIGHT 12.0

#define PIN_OUTLET_WIDTH ENTITY_OUTLET_HEIGHT
#define PIN_OUTLET_HEIGHT ENTITY_OUTLET_HEIGHT

#define PIN_OUTLET_PADDING 5.0


#define ENTITY_OUTLET_LABEL_WIDTH 100.0
#define ENTITY_OUTLET_LABEL_HEIGHT 18.0
#define ENTITY_OUTLET_PIN_PADDING 5.0
#define ENTITY_OUTLET_LABEL_PADDING_FOR_OUTPUT (PIN_OUTLET_WIDTH + ENTITY_OUTLET_PIN_PADDING)
#define ENTITY_OUTLET_LABEL_PADDING_FOR_INPUT ENTITY_OUTLET_PIN_PADDING
#define ENTITY_OUTLET_MIN_SPACING 5.0
#define ENTITY_OUTLET_WIDTH 120.0
#define ENTITY_OUTLET_FONT_SIZE ENTITY_OUTLET_HEIGHT

#define ENTITY_LABEL_PADDING 12.0
#define ENTITY_PIN_MINSPACING 1.5
#define ENTITY_PIN_HEIGHT 11.0
#define ENTITY_PIN_LEFT_PADDING 6.0
#define ENTITY_FRAME_WIDTH (ENTITY_OUTLET_WIDTH * 2)


#define ENTITY_FRAME_PADDING 5.0f

#define ENTITY_LABEL_HEIGHT 18.0
#define ENTITY_LABEL_WIDTH ENTITY_FRAME_WIDTH - ENTITY_FRAME_PADDING
#define ENTITY_LABEL_FONT_SIZE 12.0

#define CONNECTOR_LINE_WIDTH 2.0
#define ORIGIN_OFFSET 10.0
#define DESTINATION_OFFSET 20.0

